# Generated by Django 3.2.2 on 2021-05-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='leilaoitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=10)),
                ('valor_min', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='auctions.categ')),
            ],
        ),
    ]
