# Generated by Django 3.2.2 on 2021-05-18 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='leilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=10)),
                ('valor_min', models.IntegerField()),
                ('catego', models.CharField(max_length=64)),
                ('dono', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leilao_wl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wl', to='auctions.leilao')),
                ('user_wl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_wl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
