# Generated by Django 3.2.2 on 2021-05-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categ_leilaoitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leilaoitem',
            new_name='leilao',
        ),
    ]
