# Generated by Django 3.2.2 on 2021-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_leilaoitem_leilao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='cat',
            field=models.CharField(max_length=20),
        ),
    ]
