# Generated by Django 3.2.2 on 2021-05-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_categ_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
