# Generated by Django 3.2.2 on 2021-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_leilao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
    ]
